baseURL = "https://watanabe-lab.netlify.app/"
title = "Watanabe Laboratory"
theme = "PaperMod"
languageCode = "en-us"
defaultContentLanguage = "en"

[params]
  description = "Emergent Molecular Electronics Laboratory at RIKEN CEMS"
  author = "Watanabe Laboratory"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  defaultTheme = "light"
  disableThemeToggle = true
  

[[menu.main]]
  identifier = "research"
  name = "Research"
  url = "/research/"
  weight = 10

[[menu.main]]
  identifier = "people"
  name = "People"
  url = "/people/"
  weight = 20

[[menu.main]]
  identifier = "publications"
  name = "Publications"
  url = "/publications/"
  weight = 30

[[menu.main]]
  identifier = "facilities"
  name = "Facilities"
  url = "/facilities/"
  weight = 40

[[menu.main]]
  identifier = "news"
  name = "News"
  url = "/news/"
  weight = 50

[[menu.main]]
  identifier = "positions"
  name = "Open Positions"
  url = "/open-positions/"
  weight = 60

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 70

[params.assets]
  customCSS = ["css/extended/custom.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
